@apiUrl = http://0.0.0.0:8282

GET {{apiUrl}}/temp

###
GET {{apiUrl}}/rooms

###

GET {{apiUrl}}/rooms/1

###

POST {{apiUrl}}/rooms
Content-Type: application/json

{
    "room_number": 256,
    "room_type": "double",
    "price": 199
}

###

POST  {{apiUrl}}/bookings
Content-Type: application/json

{
    "guest_id": 1,
    "room_id": 3,
    "datefrom": "2025-02-12",
    "dateto": "2025-02-12"
}

###

GET  {{apiUrl}}/bookings